name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build and install liburing
      run: |
        cd liburing/liburing-0.2
        make
        sudo make install

    - name: Get go dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go test -c -o test-binary
      
    - name: Archive test binary
      uses: actions/upload-artifact@v1
      with:
        name: test-binary
        path: test-binary

    - name: Test
      run: go test -race -count=5
